name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Specify the Node.js version you need

      - name: Install dependencies
        run: |
          ls
          cd mywallstreetadvisor
          npm install
          # If using yarn, uncomment the line below and comment the line above
          # yarn install
        shell: /usr/bin/bash -e {0}

      - name: Build Next.js application
        run: |
          cd mywallstreetadvisor
          npm run build
          # If using yarn, uncomment the line below and comment the line above
          # yarn build
        shell: /usr/bin/bash -e {0}

      - name: Next to GitHub Pages
        uses: ricardobiundo/NextPagesAction@1.0.2
        with:
          username: ${{ github.actor }}
          reponame: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          gitemail: ${{ secrets.GIT_EMAIL || 'CI@example.com' }}  # Optional, default is CI@example.com
          gitname: ${{ secrets.GIT_NAME || 'CI' }}  # Optional, default is CI
          gitmsg: ${{ secrets.GIT_MSG || 'deploy' }}  # Optional, default is deploy
          cname: ${{ secrets.CNAME || '' }}  # Optional, default is none
          useyarn: true  # Optional, set to true if using yarn
        env:
          BUILD_DIR: mywallstreetadvisor  # Set the build directory for the action if needed
